begin;

create table if not exists public.users (
  id bigint generated by default as identity primary key,
  "createdAt" timestamptz not null default now(),
  name text not null,
  email text not null unique
);

insert into public.users (name, email)
select distinct on (lower(trim(email)))
  trim(name),
  lower(trim(email))
from public.registrations
where email is not null
  and trim(email) <> ''
order by lower(trim(email)), "createdAt" desc, id desc
on conflict (email) do update
set name = excluded.name;

alter table public.registrations
  add column if not exists "userId" bigint;

alter table public.registrations
  add column if not exists "eventId" bigint;

update public.registrations as registration
set "userId" = "user".id
from public.users as "user"
where registration."userId" is null
  and lower(trim(registration.email)) = "user".email;

update public.registrations as registration
set "eventId" = event.id
from public.events as event
where registration."eventId" is null
  and registration."eventTitle" = event.title
  and registration."eventDate" = event.date;

alter table public.registrations
  alter column "userId" set not null;

alter table public.registrations
  alter column "eventId" set not null;

do $$
begin
  if not exists (
    select 1
    from pg_constraint
    where conname = 'registrations_user_id_fkey'
      and conrelid = 'public.registrations'::regclass
  ) then
    alter table public.registrations
      add constraint registrations_user_id_fkey
      foreign key ("userId") references public.users (id);
  end if;
end $$;

do $$
begin
  if not exists (
    select 1
    from pg_constraint
    where conname = 'registrations_event_id_fkey'
      and conrelid = 'public.registrations'::regclass
  ) then
    alter table public.registrations
      add constraint registrations_event_id_fkey
      foreign key ("eventId") references public.events (id);
  end if;
end $$;

create index if not exists registrations_user_id_idx
  on public.registrations ("userId");

create index if not exists registrations_event_id_idx
  on public.registrations ("eventId");

alter table public.registrations
  drop column if exists name,
  drop column if exists email,
  drop column if exists "eventTitle",
  drop column if exists "eventDate",
  drop column if exists "eventLocation";

grant select, insert, update on table public.users to anon;
grant usage, select on sequence public.users_id_seq to anon;

commit;
